// <auto-generated />
using BinaAz.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinaAz.Persistence.Migrations
{
    [DbContext(typeof(BinaAzDbContext))]
    [Migration("20230731061422_addEnumKeyTable")]
    partial class addEnumKeyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinaAz.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baki"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sumqayit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zaqatala"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Astara"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yevlax"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ucar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Berde"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cebrayil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Qazax"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Quba"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ismayilli"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Siyezen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tovuz"
                        });
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Yasamal"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Suraxani"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Sebail"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Sabuncu"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Nizami"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Name = "Nesimi"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Name = "Nerimanov"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Name = "Qaradag"
                        });
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.EnumKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnumKeys");
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Settlements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 7,
                            Name = "Boyukshor"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 1,
                            Name = "Yasamal"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 1,
                            Name = "Yeni Yasamal"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 5,
                            Name = "8-ci kilometr"
                        },
                        new
                        {
                            Id = 5,
                            DistrictId = 5,
                            Name = "Keshle"
                        },
                        new
                        {
                            Id = 6,
                            DistrictId = 6,
                            Name = "Kubinka"
                        },
                        new
                        {
                            Id = 7,
                            DistrictId = 6,
                            Name = "1-ci Mikrorayon"
                        },
                        new
                        {
                            Id = 8,
                            DistrictId = 6,
                            Name = "2-ci Mikrorayon"
                        });
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.District", b =>
                {
                    b.HasOne("BinaAz.Domain.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("BinaAz.Domain.Entities.District", "District")
                        .WithMany("Settlements")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("BinaAz.Domain.Entities.District", b =>
                {
                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
