// <auto-generated />
using BinaAz.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinaAz.Persistence.Migrations
{
    [DbContext(typeof(BinaAzDbContext))]
    [Migration("20230731055441_addCityTable")]
    partial class addCityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinaAz.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baki"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sumqayit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zaqatala"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Astara"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yevlax"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ucar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Berde"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cebrayil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Qazax"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Quba"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ismayilli"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Siyezen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tovuz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
